Update TeamWin-TWRP.yml

diff --git a/.github/workflows/TeamWin-TWRP.yml b/.github/workflows/TeamWin-TWRP.yml
--- a/.github/workflows/TeamWin-TWRP.yml
+++ b/.github/workflows/TeamWin-TWRP.yml
@@ -4,55 +4,60 @@ on:
   workflow_dispatch:
     inputs:
       DEVICE_NAME:
-      required: true
-      default: ''
-      type: string
+        description: 'Device Name'
+        required: true
+        default: ''
+        type: string
       BUILD_DESCRIPTION:
-       required: true
-       default: 'Enter build description'
-       type: string
+        description: 'Build Description'
+        required: true
+        default: 'Enter build description'
+        type: string
       MANIFEST_BRANCH:
         description: 'TWRP Manifest Branch'
         required: true
         default: ''
         type: choice
         options:
-        - twrp-12.1
-        - twrp-11
-        - twrp-10.0-deprecated
-        - twrp-9.0
-        - twrp-8.1
-        - twrp-8.1-macOS
-        - twrp-7.1
-        - twrp-6.0
-        - twrp-5.1
-        - twrp-4.4-deprecated
+          - twrp-12.1
+          - twrp-11
+          - twrp-10.0-deprecated
+          - twrp-9.0
+          - twrp-8.1
+          - twrp-8.1-macOS
+          - twrp-7.1
+          - twrp-6.0
+          - twrp-5.1
+          - twrp-4.4-deprecated
       DEVICE_TREE:
         description: 'Custom Recovery Tree' # Your already made Device Tree for TWRP
         required: true
         default: 'https://github.com/lazycodebuilder/recovery_rmx1851'
+        type: string
       DEVICE_TREE_BRANCH:
         description: 'Custom Recovery Tree Branch' # Your Device Tree Branch, make sure it's right.
         required: true
         default: 'android-14'
+        type: string
       BUILD_TARGET:
-        description: 'Specify your Build Target' # Pick among boot, recovery and vendor_boot
+        description: 'Specify your Build Target' # Pick among boot, recovery, and vendor_boot
         required: true
         default: 'recovery'
         type: choice
         options:
-        - boot
-        - recovery
-        - vendorboot
+          - boot
+          - recovery
+          - vendor_boot
       LDCHECK:
         description: 'Use LDCHECK'
         required: false
         default: 'false'
         type: boolean
       LDCHECKPATH:
-        description: 'Path of blobs to check' # Use it know what kind of dependencies your missing for decryption blobs.
+        description: 'Path of blobs to check' # Use it to know what kind of dependencies you're missing for decryption blobs.
         required: true
         default: 'system/bin/qseecomd'
+        type: string
 
 jobs:
   build:
@@ -64,11 +69,11 @@ jobs:
     permissions:
       contents: write
     steps:
-    - name: Check Out
-      uses: actions/checkout@v4
+      - name: Check Out
+        uses: actions/checkout@v4
 
-    - name: Send Start Notification
-      run: |
+      - name: Send Start Notification
+        run: |
           ACTION_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
           curl -X POST https://api.telegram.org/bot5477489617:AAHFxTxuvPGgGM_QmoWtIYBPouv-OnTHL64/sendMessage \
             -d chat_id="-1001538361307" \
@@ -76,159 +81,160 @@ jobs:
             Description: ${{ github.event.inputs.BUILD_DESCRIPTION }} \
             [View Actions]($ACTION_URL)" \
             -d parse_mode="Markdown"
-      
-    - name: Display Inputs
-      run: |
-        echo "Displaying variables/inputs."
-        echo "Manifest Branch: ${{ inputs.MANIFEST_BRANCH }}"
-        echo "Device Tree: ${{ inputs.DEVICE_TREE }}"
-        echo "Device Branch: ${{ inputs.DEVICE_TREE_BRANCH }}"
-        echo "Build Target: ${{ inputs.BUILD_TARGET }}image"
 
-    - name: Cleanup
-      uses: rokibhasansagar/slimhub_actions@main
-      
-    - name: Set Swap Space
-      uses: pierotofy/set-swap-space@master
-      with:
-        swap-size-gb: 12
+      - name: Display Inputs
+        run: |
+          echo "Displaying variables/inputs."
+          echo "Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}"
+          echo "Device Tree: ${{ github.event.inputs.DEVICE_TREE }}"
+          echo "Device Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
+          echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}image"
 
-    - name: Check Manifest Branch
-      run: |
-        if [ ${{ inputs.MANIFEST_BRANCH }} == 'twrp-11' ] || [ ${{ inputs.MANIFEST_BRANCH }} == 'twrp-12.1' ]; then
-            echo "MANIFEST=https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git" >> $GITHUB_ENV
-            echo "CHECK_LEGACY_BRANCH=false" >> $GITHUB_ENV
-        else
-            echo "MANIFEST=https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git" >> $GITHUB_ENV
-            echo "CHECK_LEGACY_BRANCH=true" >> $GITHUB_ENV
-        fi
+      - name: Cleanup
+        run: |
+          rm -rf android-recovery
 
-    - name: Prepare the environment
-      run: |
-        sudo apt update
-        sudo apt -y upgrade
-        sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libtinfo5 libgflags-dev libncurses5 python3
+      - name: Set Swap Space
+        uses: pierotofy/set-swap-space@master
+        with:
+          swap-size-gb: 12
 
-    - name: Install OpenJDK
-      uses: actions/setup-java@v4
-      with:
-        distribution: 'zulu'
-        java-version: '8'
+      - name: Check Manifest Branch
+        run: |
+          if [ "${{ github.event.inputs.MANIFEST_BRANCH }}" == 'twrp-11' ] || [ "${{ github.event.inputs.MANIFEST_BRANCH }}" == 'twrp-12.1' ]; then
+              echo "MANIFEST=https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git" >> $GITHUB_ENV
+              echo "CHECK_LEGACY_BRANCH=false" >> $GITHUB_ENV
+          else
+              echo "MANIFEST=https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git" >> $GITHUB_ENV
+              echo "CHECK_LEGACY_BRANCH=true" >> $GITHUB_ENV
+          fi
 
-    - name: Install Git-Repo
-      run: |
-        mkdir ~/bin
-        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
-        chmod a+x ~/bin/repo
-        sudo ln -sf ~/bin/repo /usr/bin/repo
+      - name: Prepare the environment
+        run: |
+          sudo apt update
+          sudo apt -y upgrade
+          sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libtinfo5 libgflags-dev libncurses5 python3
 
-    - name: Initialize Repo
-      run: |
-        mkdir android-recovery
-        cd android-recovery
-        git config --global user.name "lazycodebuilder"
-        git config --global user.email "154446636+lazycodebuilder@users.noreply.github.com"
-        repo init --depth=1 -u ${{ env.MANIFEST }} -b ${{ inputs.MANIFEST_BRANCH }}
+      - name: Install OpenJDK
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'zulu'
+          java-version: '8'
 
-    - name: Repo Sync
-      run: |
-        cd android-recovery
-        repo sync -j$(nproc --all) --force-sync
-      
-    - name: Clone Device Tree
-      run: |
-        cd android-recovery
-        git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ./device_tree
-        cd device_tree
-        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
+      - name: Install Git-Repo
+        run: |
+          mkdir ~/bin
+          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
+          chmod a+x ~/bin/repo
+          sudo ln -sf ~/bin/repo /usr/bin/repo
 
-    - name: Extracting variables from .mk file
-      run: |
-        cd android-recovery/device_tree
-        # Initialize variables
-        DEVICE_MAKEFILE=""
-        DEVICE_DIRECTORY=""
-        DEVICE_NAME=""
-        # Loop through each .mk file in the current directory
-        for file in *.mk; do
-            # Extract variables using sed
-            makefile=$(sed -n 's/^[[:space:]]*PRODUCT_NAME[[:space:]]*:=\s*\(.*\)/\1/p' "$file")
-            brand=$(sed -n 's/^[[:space:]]*PRODUCT_BRAND[[:space:]]*:=\s*\(.*\)/\1/p' "$file")
-            codename=$(sed -n 's/^[[:space:]]*PRODUCT_DEVICE[[:space:]]*:=\s*\(.*\)/\1/p' "$file")
-            if [[ -n "$makefile" && -n "$brand" && -n "$codename" ]]; then
-                DEVICE_MAKEFILE="$makefile"
-                DEVICE_DIRECTORY="device/$brand"
-                DEVICE_NAME="$codename"
-                echo "DEVICE_MAKEFILE=${DEVICE_MAKEFILE}" >> $GITHUB_ENV
-                echo "DEVICE_NAME=${DEVICE_NAME}" >> $GITHUB_ENV
-                echo "DEVICE_DIRECTORY=${DEVICE_DIRECTORY}" >> $GITHUB_ENV
-                break
-            fi
-        done
-        # Navigate to the parent directory
-        cd ../
-        # Create the necessary directories
-        echo "Creating directory: $DEVICE_DIRECTORY"
-        mkdir -p "$DEVICE_DIRECTORY"
-        # Move device_tree folder to device_directory and rename it to $DEVICE_NAME
-        echo "Moving device_tree to $DEVICE_DIRECTORY/$DEVICE_NAME"
-        mv device_tree "$DEVICE_DIRECTORY"/"$DEVICE_NAME"
+      - name: Initialize Repo
+        run: |
+          mkdir android-recovery
+          cd android-recovery
+          git config --global user.name "lazycodebuilder"
+          git config --global user.email "154446636+lazycodebuilder@users.noreply.github.com"
+          repo init --depth=1 -u ${{ env.MANIFEST }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
 
-    - name: Installing python2 for legacy builds
-      if: env.CHECK_LEGACY_BRANCH == 'true'
-      run: |
-        sudo apt-get install python2 python-is-python2
+      - name: Repo Sync
+        run: |
+          cd android-recovery
+          repo sync -j$(nproc --all) --force-sync
 
-    - name: Building Image 
-      run: |
-        cd android-recovery
-        source build/envsetup.sh
-        export ALLOW_MISSING_DEPENDENCIES=true
-        lunch ${{ env.DEVICE_MAKEFILE }}-eng && make clean && make ${{ inputs.BUILD_TARGET }}image -j$(nproc --all)
-        echo "Done building your ${{ inputs.BUILD_TARGET }}.img"
+      - name: Clone Device Tree
+        run: |
+          cd android-recovery
+          git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./device_tree
+          cd device_tree
+          echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
 
-    - name: Set build target for upload
-      run: |
-        if [ ${{ inputs.BUILD_TARGET }} == 'recovery' ]; then
-           echo "BUILD_TARGET_NAME=recovery" >> $GITHUB_ENV
-        elif [ ${{ inputs.BUILD_TARGET }} == 'boot' ]; then
-           echo "BUILD_TARGET_NAME=boot" >> $GITHUB_ENV
-        else
-           echo "BUILD_TARGET_NAME=vendor_boot" >> $GITHUB_ENV
-        fi
+      - name: Extracting variables from .mk file
+        run: |
+          cd android-recovery/device_tree
+          # Initialize variables
+          DEVICE_MAKEFILE=""
+          DEVICE_DIRECTORY=""
+          DEVICE_NAME=""
+          # Loop through each .mk file in the current directory
+          for file in *.mk; do
+              # Extract variables using sed
+              makefile=$(sed -n 's/^[[:space:]]*PRODUCT_NAME[[:space:]]*:=\s*\(.*\)/\1/p' "$file")
+              brand=$(sed -n 's/^[[:space:]]*PRODUCT_BRAND[[:space:]]*:=\s*\(.*\)/\1/p' "$file")
+              codename=$(sed -n 's/^[[:space:]]*PRODUCT_DEVICE[[:space:]]*:=\s*\(.*\)/\1/p' "$file")
+              if [[ -n "$makefile" && -n "$brand" && -n "$codename" ]]; then
+                  DEVICE_MAKEFILE="$makefile"
+                  DEVICE_DIRECTORY="device/$brand"
+                  DEVICE_NAME="$codename"
+                  echo "DEVICE_MAKEFILE=${DEVICE_MAKEFILE}" >> $GITHUB_ENV
+                  echo "DEVICE_NAME=${DEVICE_NAME}" >> $GITHUB_ENV
+                  echo "DEVICE_DIRECTORY=${DEVICE_DIRECTORY}" >> $GITHUB_ENV
+                  break
+              fi
+          done
+          # Navigate to the parent directory
+          cd ../
+          # Create the necessary directories
+          echo "Creating directory: $DEVICE_DIRECTORY"
+          mkdir -p "$DEVICE_DIRECTORY"
+          # Move device_tree folder to device_directory and rename it to $DEVICE_NAME
+          echo "Moving device_tree to $DEVICE_DIRECTORY/$DEVICE_NAME"
+          mv device_tree "$DEVICE_DIRECTORY"/"$DEVICE_NAME"
 
-    - name: Set Build Date # Output will be use in Release
-      run: |
-        echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
-      
-    - name: Upload to Release
-      uses: softprops/action-gh-release@master
-      with:
-        files: |
-          android-recovery/out/target/product/${{ env.DEVICE_NAME }}/${{ env.BUILD_TARGET_NAME }}.img
-          android-recovery/out/target/product/${{ env.DEVICE_NAME }}/*installer*zip
-          android-recovery/out/target/product/${{ env.DEVICE_NAME }}/ramdisk-recovery.*
-        name: Unofficial TWRP for ${{ env.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
-        tag_name: ${{ github.run_id }}
-        body: |
-          Build: ${{ inputs.MANIFEST_BRANCH }}
-          Device: [Device Tree/Branch](${{ inputs.DEVICE_TREE }}/tree/${{ inputs.DEVICE_TREE_BRANCH }})
-          Commit: Most recent [commit](${{ inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
+      - name: Installing python2 for legacy builds
+        if: env.CHECK_LEGACY_BRANCH == 'true'
+        run: |
+          sudo apt-get install python2 python-is-python2
 
-    - name: Send Success Notification
-      if: success()
-      run: |
+      - name: Building Image
+        run: |
+          cd android-recovery
+          source build/envsetup.sh
+          export ALLOW_MISSING_DEPENDENCIES=true
+          lunch ${{ env.DEVICE_MAKEFILE }}-eng && make clean && make ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)
+          echo "Done building your ${{ github.event.inputs.BUILD_TARGET }}.img"
+
+      - name: Set build target for upload
+        run: |
+          if [ "${{ github.event.inputs.BUILD_TARGET }}" == 'recovery' ]; then
+             echo "BUILD_TARGET_NAME=recovery" >> $GITHUB_ENV
+          elif [ "${{ github.event.inputs.BUILD_TARGET }}" == 'boot' ]; then
+             echo "BUILD_TARGET_NAME=boot" >> $GITHUB_ENV
+          else
+             echo "BUILD_TARGET_NAME=vendor_boot" >> $GITHUB_ENV
+          fi
+
+      - name: Set Build Date # Output will be used in Release
+        run: |
+          echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
+
+      - name: Upload to Release
+        uses: softprops/action-gh-release@master
+        with:
+          files: |
+            android-recovery/out/target/product/${{ env.DEVICE_NAME }}/${{ env.BUILD_TARGET_NAME }}.img
+            android-recovery/out/target/product/${{ env.DEVICE_NAME }}/*installer*zip
+            android-recovery/out/target/product/${{ env.DEVICE_NAME }}/ramdisk-recovery.*
+          name: Unofficial TWRP for ${{ env.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
+          tag_name: ${{ github.run_id }}
+          body: |
+            Build: ${{ github.event.inputs.MANIFEST_BRANCH }}
+            Device: [Device Tree/Branch](${{ github.event.inputs.DEVICE_TREE }}/tree/${{ github.event.inputs.DEVICE_TREE_BRANCH }})
+            Commit: Most recent [commit](${{ github.event.inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
+
+      - name: Send Success Notification
+        if: success()
+        run: |
           RELEASE_LINK="https://github.com/${{ github.repository }}/releases"
           curl -X POST https://api.telegram.org/bot5477489617:AAHFxTxuvPGgGM_QmoWtIYBPouv-OnTHL64/sendMessage \
             -d chat_id="-1001538361307" \
             -d text="✅ Build TWRP finished successfully for target: ${{ github.event.inputs.DEVICE_NAME }}. \
             Description: ${{ github.event.inputs.BUILD_DESCRIPTION }} \
-            [Download TWRP](${RELEASE_LINK}) \
+            [Download TWRP](${RELEASE_LINK})" \
             -d parse_mode="Markdown"
 
-    - name: Send Failure Notification
-      if: failure()
-      run: |
+      - name: Send Failure Notification
+        if: failure()
+        run: |
           ACTION_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
           curl -X POST https://api.telegram.org/bot5477489617:AAHFxTxuvPGgGM_QmoWtIYBPouv-OnTHL64/sendMessage \
             -d chat_id="-1001538361307" \
@@ -237,13 +243,16 @@ jobs:
             [View Actions]($ACTION_URL)" \
             -d parse_mode="Markdown"
 
-    - name: Run LDCheck
-      if: inputs.LDCHECK == 'true'
-      run: |
-        cd tools
-        mv -n libneeds ${GITHUB_WORKSPACE}/android-recovery/out/target/product/${{ env.DEVICE_NAME }}/recovery/root/
-        mv -n ldcheck ${GITHUB_WORKSPACE}/android-recovery/out/target/product/${{ env.DEVICE_NAME }}/recovery/root/
-        cd ../android-recovery/out/target/product/${{ env.DEVICE_NAME }}/recovery/root
-        python3 ldcheck -p system/lib64:vendor/lib64:system/lib:vendor/lib -d ${{ inputs.LDCHECKPATH }}
-        echo "Done checking missing dependencies. Review, and reconfigure your tree."
-      continue-on-error: true
+      - name: Run LDCheck
+        if: inputs.LDCHECK == 'true'
+        run: |
+          cd tools
+          mv -n libneeds ${GITHUB_WORKSPACE}/android-recovery/out/target/product/${{ env.DEVICE_NAME }}/recovery/root/
+          mv -n ldcheck ${GITHUB_WORKSPACE}/android-recovery/out/target/product/${{ env.DEVICE_NAME }}/recovery/root/
+          cd ../android-recovery/out/target/product/${{ env.DEVICE_NAME }}/recovery/root
+          if ! python3 ldcheck -p system/lib64:vendor/lib64:system/lib:vendor/lib -d ${{ github.event.inputs.LDCHECKPATH }}; then
+              echo "LDCheck failed. Review the output for missing dependencies."
+              exit 1
+          fi
+          echo "Done checking missing dependencies. Review, and reconfigure your tree."
+        continue-on-error: true
